'use client'

import 'bootstrap/dist/css/bootstrap.min.css';
// import type { Metadata } fr'm 'n'xt';
import localFont from 'next/font/local';
import './globals.css';
import NavbarTop from '@/frontend/component/layout/navbar-top';
import Footer from '@/frontend/component/layout/footer';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column min-vh-100`}>
        <header>
          <NavbarTop />
        </header>

        <main className="container">
          {children}
        </main>

        <Footer className="mt-auto" />
      </body>
    </html>
  );
}
